# Generated by Django 4.2.7 on 2023-11-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.CharField(default='this record created before adding note coloumn', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(null=True, related_name='authors', to='books_authors_app.book'),
        ),
    ]
