# Generated by Django 4.2.7 on 2023-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged',
            field=models.BooleanField(default=0),
        ),
    ]
