# Generated by Django 4.2.7 on 2023-11-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_is_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_logged',
        ),
    ]
