# Generated by Django 4.2.7 on 2023-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='skeptics',
            field=models.ManyToManyField(related_name='skeptics', to='app.user'),
        ),
    ]
