# Generated by Django 4.2.7 on 2023-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_note_alter_author_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='note',
            field=models.TextField(),
        ),
    ]
